//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zahard_Student
{
    using System;
    using System.Collections.Generic;
    
    public partial class professor
    {
        public string professor_name { get; set; }
        public string password { get; set; }
    }
}
