//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zahard_Student
{
    using System;
    using System.Collections.Generic;
    
    public partial class students
    {
        public int student_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public int groups { get; set; }
        public decimal test { get; set; }
        public decimal exam { get; set; }
        public decimal rate { get; set; }
    }
}
